// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIJ2Oq9a138x4RgNaVA7sxizUF9FEUyfo',
    appId: '1:856192356591:web:598be83e9465c26e308b1a',
    messagingSenderId: '856192356591',
    projectId: 'cyberpunk-character-creator',
    authDomain: 'cyberpunk-character-creator.firebaseapp.com',
    storageBucket: 'cyberpunk-character-creator.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVzRI4u3zIOTXgnXhGc90cVa_6P52aSEw',
    appId: '1:856192356591:android:c1524a320157600d308b1a',
    messagingSenderId: '856192356591',
    projectId: 'cyberpunk-character-creator',
    storageBucket: 'cyberpunk-character-creator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbok3AFICrH7nrPJjh-KlVSJBqc-y7B3w',
    appId: '1:856192356591:ios:42b932c2264d77c3308b1a',
    messagingSenderId: '856192356591',
    projectId: 'cyberpunk-character-creator',
    storageBucket: 'cyberpunk-character-creator.appspot.com',
    iosClientId: '856192356591-resjeavjeccbfikac607fdb9h5k6anu6.apps.googleusercontent.com',
    iosBundleId: 'com.example.characterCreator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbok3AFICrH7nrPJjh-KlVSJBqc-y7B3w',
    appId: '1:856192356591:ios:42b932c2264d77c3308b1a',
    messagingSenderId: '856192356591',
    projectId: 'cyberpunk-character-creator',
    storageBucket: 'cyberpunk-character-creator.appspot.com',
    iosClientId: '856192356591-resjeavjeccbfikac607fdb9h5k6anu6.apps.googleusercontent.com',
    iosBundleId: 'com.example.characterCreator',
  );
}
